[package]
name = "stationeering_mips"
version = "0.1.0"
edition = "2018"

[dependencies]
once_cell = "1.8.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
structopt = "0.3.23"
